// <auto-generated />
using System;
using DRB_TEMP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DRB_TEMP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604111233_AddTemperatureDailyLogs")]
    partial class AddTemperatureDailyLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DRB_TEMP.Models.TemperatureDailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DoAm")
                        .HasColumnType("float");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NhietDo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TemperatureDailyLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
